-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyHintsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyLimitResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dailyScoresUsed" INTEGER NOT NULL DEFAULT 0;
